### ISSUE TITLE
Wood Shop, Dust Collection, Remote Missing

### ISSUE THREAD

**Issue by boomalator** [Protospace/ProjectTrackingTest#2]
Does anyone know what happened to the remote switch for the dust collector?

**Comment by ProtospaceInfrastructure** [comment]
It was found yesterday. It is tywraped to the duct next to the tablesaw
presently

**Comment by boomalator** [comment]
This is a test for tonight, but cool. 

However, please log in with your own account not the infrastructure account.

**Comment by ProtospaceInfrastructure** [comment]
Im pretty sure this is my account, it has my name on it

**Comment by boomalator** [comment]
It shows as "Protospace Infrastructure commented..."
